#Here is where you will specify what items you want to disable the crafting of.
# !!! item IDs or data tags are not allowed, only material names (Use 1.16 material list if needing to use data tags) !!!
disable-crafting:
  - HOPPER
