#For help with the configuration file, please visit DisableCrafting's wiki page here:
# https://github.com/matthew-wiggins/DisableCrafting/wiki

items:
  world:
    - HOPPER;dc.world.hopper
  world_nether:
    - HOPPER;dc.world_nether.hopper
  world_the_end:
    - HOPPER;dc.world_the_end.hopper
